services:
  api:
    image: ${ECR_REGISTRY:-kirkedev}/mpr-api:${TAG}
    environment:
      MPR_URL: https://mpr.datamart.ams.usda.gov

  app:
    image: ${ECR_REGISTRY:-kirkedev}/mpr-app:${TAG}
    ports:
      - "80:80"
    depends_on:
      - api
