version: "3.9"

services:
  mpr:
    build:
      context: test/mpr

  api:
    build:
      dockerfile: api/Dockerfile
      target: dev
    environment:
      MPR_URL: http://mpr:3000
    ports:
      - "9229:9229"
    volumes:
      - ./api:/home/node/mpr/api:ro
      - ./lib:/home/node/mpr/lib:ro
    depends_on:
      - mpr

  app:
    build:
      dockerfile: app/Dockerfile
      target: dev
    environment:
      API_URL: http://api:3000
    volumes:
      - ./app:/home/node/mpr/app:ro
      - ./lib:/home/node/mpr/lib:ro
    ports:
      - "3000:3000"
    depends_on:
      - api
