version: "3.9"

services:
  sut:
    build:
      dockerfile: test/Dockerfile
    environment:
      CYPRESS_BASE_URL: http://app
    depends_on:
      - app

  app:
    build:
      dockerfile: app/Dockerfile
    depends_on:
      - api

  api:
    build:
      dockerfile: api/Dockerfile
    environment:
      MPR_URL: http://mpr:3000
    healthcheck:
      test: ["CMD-SHELL", "yarn workspace api healthy"]
      interval: 1s
      retries: 10
    depends_on:
      - mpr

  mpr:
    build:
      context: test/mpr
