version: "3.9"

services:
  mpr:
    build:
      context: test/mpr
    environment:
      MPR_PORT: ${MPR_PORT:-80}

  api:
    build:
      dockerfile: api/Dockerfile
      target: dev
    environment:
      API_PORT: ${API_PORT}
      MPR_URL: ${MPR_HOST}:${MPR_PORT:-80}
    ports:
      - "9229:9229"
      - ${API_PORT}:${API_PORT}
    volumes:
        - ./build/api:/home/node/mpr/api
        - ./build/lib:/home/node/mpr/lib
        - ./api/package.json:/home/node/mpr/api/package.json
        - ./lib/package.json:/home/node/mpr/lib/package.json
    depends_on:
      - mpr
