version: "3.9"

services:
  sut:
    build:
      dockerfile: test/Dockerfile
    environment:
      CYPRESS_BASE_URL: http://api:${API_PORT}
    depends_on:
      - api

  api:
    build:
      dockerfile: api/Dockerfile
    environment:
      API_PORT: ${API_PORT}
      MPR_URL: ${MPR_HOST}:${MPR_PORT:-80}
    expose:
      - ${API_PORT}
    healthcheck:
      test: ["CMD-SHELL", "yarn workspace api healthy"]
      interval: 1s
      retries: 10
    depends_on:
      - mpr

  mpr:
    build:
      context: test/mpr
    environment:
      MPR_PORT: ${MPR_PORT:-80}
    expose:
      - ${MPR_PORT:-80}
