name: Acceptance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build docker images
        run: yarn build

      - name: Start app
        run: yarn start

      - name: Run acceptance tests
        env:
          CYPRESS_BASE_URL: http://localhost
        run: yarn workspace features test
