name: Acceptance Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Start app
        run: yarn dev -d

      - name: Run acceptance tests
        run: yarn workspace test e2e
