name: Deploy

on:
  push:
    tags:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Build docker images
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
        run: yarn build

      - name: Publish images to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
        run: yarn publish

      - name: Create AWS docker context
        run: docker context create ecs mpr

      - name: Deploy to ECS
        run: docker compose -f docker-compose.yaml --project-name mpr --context mpr up
