name: Deploy

on:
  push:
    tags:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Build docker images
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
        run: yarn build

      - name: Publish images to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
        run: yarn publish

      - name: Use Docker compose CLI
        run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: Use ECS context
        run: | 
            docker context create ecs mpr --from-env
            docker context use mpr

      - name: Deploy images to ECS
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
        run: yarn start
