name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn workspace test unit

  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Install playwright
        run: yarn workspace test playwright install

      - name: Run acceptance tests
        run: yarn workspace test e2e

      - name: Shutdown app
        if: always()
        run: yarn stop
        continue-on-error: true
