name: Merge

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run smoke tests
        run: yarn workspace test smoke

      - name: Shutdown app
        if: always()
        run: yarn stop
        continue-on-error: true
