name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn workspace test unit

      - name: Upload unit test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: test
          flag-name: unit
          parallel: true

      - name: Run integration tests
        run: yarn workspace test integration

      - name: Upload integration test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: test
          flag-name: integration
          parallel-finished: true
