name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Run all tests
        run: yarn workspace test all
